### ISSUE TITLE
Crashes when generating invoice

### ISSUE THREAD

**Issue by dgrabla** [ixti/gnucash-invoice#7]
This works:

```
> gnucash-invoice --dbpath /tmp/test.gnucash 
001           Company                            (2014/09/30) [2014/09/30]
```

But it cannot generate the invoice:

```
> gnucash-invoice --dbpath /tmp/test.gnucash 001
/usr/lib/ruby/1.9.1/pathname.rb:363:in `initialize': can't convert nil into String (TypeError)
        from /usr/lib/ruby/1.9.1/pathname.rb:363:in `new'
        from /usr/lib/ruby/1.9.1/pathname.rb:363:in `join'
        from /var/lib/gems/1.9.1/gems/gnucash-invoice-0.1.3/lib/gnucash/invoice/printer.rb:11:in `initialize'
        from /var/lib/gems/1.9.1/gems/gnucash-invoice-0.1.3/lib/gnucash/invoice/runner.rb:20:in `new'
        from /var/lib/gems/1.9.1/gems/gnucash-invoice-0.1.3/lib/gnucash/invoice/runner.rb:20:in `run'
        from /var/lib/gems/1.9.1/gems/gnucash-invoice-0.1.3/bin/gnucash-invoice:8:in `<top (required)>'
        from /usr/local/bin/gnucash-invoice:23:in `load'
        from /usr/local/bin/gnucash-invoice:23:in `<main>'
```

**Comment by dgrabla** [comment]
Fix confirmed, thanks
